name: API Performance Test
on: push
jobs:
  performance-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman

      - name: Run Performance Test
        run: |
          mkdir -p newman
          newman run cat-api-performance.json \
          --iteration-count 100 \
          --reporters cli,html \
          --reporter-html-export newman/report.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: performance-report
          path: newman/report.html
